### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [htr-tech/pakcrack#5]

**Comment by htr-tech** [comment]
@graysuit dude this script clones random Facebook accounts with weakest password 😓 
this script generates random numbers & tries each number 😅

**Comment by graysuit** [comment]
@htr-tech 
lol ! Interesting. 
so where's code ?

`> Run : python2 crack.py`
crack.py is binary zip. How do I get code to understand and learn more about that functionality.

What I understand is that
```
- Generate random pakistani numbers
- Generate random passwords
- Try to login facebook with pakistani numbers & passwords
```
Right ?

**Comment by htr-tech** [comment]
@graysuit not random passwords it tries with the last 6/7 digits of those numbers 😅

**Comment by htr-tech** [comment]
> @htr-tech
> lol ! Interesting.
> so where's code ?
> 
> `> Run : python2 crack.py`
> crack.py is binary zip. How do I get code to understand and learn more about that functionality.
> 
> What I understand is that
> 
> ```
> - Generate random pakistani numbers
> - Generate random passwords
> - Try to login facebook with pakistani numbers & passwords
> ```
> 
> Right ?

try to reverse it 😈 it will be a practice for you 💘

**Comment by graysuit** [comment]
> try to reverse it 😈 it will be a practice for you 💘

@htr-tech 
Can you give me any hint ? I didn't worked with py and pyc much.
Is this hint :https://stackoverflow.com/questions/5287253/is-it-possible-to-decompile-a-compiled-pyc-file-into-a-py-file ?

**Comment by htr-tech** [comment]
@graysuit you have to work on python dis in order to decompile it 😈

**Comment by chibsah1988** [comment]
Am in Ghana but I install everything Don 4th know hot to use it
